### ISSUE TITLE
g:nv_use_short_pathnames must be declared

### ISSUE THREAD

**Issue by sdothum** [Alok/notational-fzf-vim#18] opened 2018-01-22 01:50 UTC
This problem has probably gone unnoticed because who wouldn't set it on :) otherwise a vim error occurs on execution.

On a side note, any chance of re-implementing ag and allowing a choice of using ag or rg? For some reason I have found ag more reliable than rg on my systems -- rg seems to omit scanning certain subdirectories from what I can tell, don't know why. To get around that I have had to add redundant subdirectory entries in my g:nv_search_paths.

Great plugin by the way!

**Comment by Alok** [comment] 2018-01-22 01:54
`ag` won't be implemented.

I'll look at the issue later this week, busy for the next few days.

**Comment by sdothum** [comment] 2018-01-22 05:33
Found my problem with incomplete rg results: I needed to creata a rg wrapper to enforce --unrestricted (and added --ignore-files a la .agignore). So results are as expected.

**Comment by Alok** [comment] 2018-01-24 01:16
i'm not seeing how this error would arise. please send your nv config and
make sure you're using the latest version. screenshot the error message
too, to make it easy on me.


-- Alok

**Comment by sdothum** [comment] 2018-01-24 03:07
Actually, I discovered this error from a [reddit post](https://www.reddit.com/r/vim/comments/7rd8ru/cant_get_this_notational_plugin_to_work/) which I was able to reproduce by commenting out my "let g:nv_use_short_pathnames=1"

**Comment by Alok** [comment] 2018-01-24 21:54
That doesn't really reproduce it since it just avoids the conditional branch that contains the actually problematic line. As far as I can tell, it's something to do with either `shellescape` or `expand('<sfile>:p:h:h')`. Maybe their directory path has spaces or odd characters like parens in it.

**Comment by Alok** [comment] 2018-02-09 01:52
try now

**Comment by johnoshea** [comment] 2018-02-09 01:54
Fixed! That's a *super* quick response - thank you!

**Comment by Alok** [comment] 2018-02-10 05:56
18 days ain't that quick mate

**Closed by Alok** 2018-02-10 05:56 UTC
