### ISSUE TITLE
index out of range error when closing fzf terminal buffer with notational-fzf-vim

### ISSUE THREAD

**Issue by viniciusarcanjo** [Alok/notational-fzf-vim#8] opened 2017-03-04 17:50 UTC
Hi @Alok, 

With this minimal config, I'm getting this error when quitting fzf terminal buffer: 
```
nnoremap <silent> <LocalLeader>n :NV<CR>
" fzf-nv directories
let g:nv_directories = ['~/repos/.wiki', './doc', './docs', './note', './notes']
```

I found out this problem when I was trying to create a note, but I changed my mind as I was typing and decided to quit the fzf buffer. For example, to reproduce the issue:

1 - fire up :NV 
2 - hit escape " (the user changed his mind, he wants to quit)
3 - :q  " to quit the fzf buffer 
4 - note the following error:

```
Error detected while processing function 31[30]..<SNR>43_callback:                                                                                                                             
line   33:                                                                                                                                                                                     
Vim(let):E684: list index out of range: 0  
```

BTW, I'm running neovim 0.2, a normal fzf buffer doesn't not result in this error, so I believe it has to do with the way your plugin exits. I tried looking up into the code, but I'm a beginner with vim/neovim so I barely know VimScript.

Thanks for this plugin! It's awesome!

**Comment by Alok** [comment] 2017-03-04 21:28
I'm not seeing this issue, but try the latest commit. Also, what version of fzf do you have (`fzf --version`)?

**Comment by viniciusarcanjo** [comment] 2017-03-06 02:08
I just compiled nvim 0.2 with the latest commit (e32ec03), still I get the same error. That's weird. 

```
~/.config/nvim
❯ nvim --version
NVIM v0.2.0-762-ge32ec03
Build type: RelWithDebInfo
....
Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui

~/.config/nvim
❯ fzf --version
0.16.6
```

About the code it is quite clear though, which is why I don't understand where this `"function 31[30]..<SNR>43_callback: line 33"` is coming from. 

I'm trying to figure out if I have another conflicting plug-in or something. It's funny though that a normal fzf terminal buffer, without the :NV wrapper, this error doesn't show up. Thank you for your time.

**Comment by Alok** [comment] 2017-03-06 07:03
I'm not sure that's part of my plugin. If you profile vim, you can see where the function is called from. Maybe you have some other mapping or setting conflicting with closing the buffer?

**Comment by Alok** [comment] 2017-03-11 21:28
Closing since I couldn't reproduce it. Feel free to re-open it.

**Closed by Alok** 2017-03-11 21:28 UTC
